version: "3.9"

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    image: boxmove
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
      DB_PORT: 27017
      DB_USER: boxmove
      DB_PASS: boxmoveSecret
      DB_NAME: boxmove
      HTTP_ADDR: :3000
    links:
      - database:database
    depends_on:
      - database
    restart: always

  database:
    container_name: database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: boxmove
      MONGO_INITDB_ROOT_USERNAME: boxmove
      MONGO_INITDB_ROOT_PASSWORD: boxmoveSecret
    ports:
      - 27017:27017
    restart: always