version: "3.9"

services:

  boxmove:
    container_name: boxmove
    build:
      context: .
      dockerfile: Dockerfile
    image: boxmove
    ports:
      - 3000:3000
    environment:
      DB_URI: mongodb://database:27017
      DB_NAME: boxmove
      HTTP_ADDR: :3000
    links:
      - database:database
    depends_on:
      - database
    restart: always

  database:
    container_name: database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: boxmove
    ports:
      - 27017:27017
    restart: always